export { default as Home } from './Home/Home'
export { default as SignIn } from './SignIn/SignIn'
export { default as SignUp } from './SignUp/SignUp'
export { default as Restaurant } from './Restaurant/Restaurant'
export { default as Category } from './Category/Category'
